from enum import StrEnum

class ErrorCode(StrEnum):
    INVALID_INPUT = "INVALID_INPUT"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    DEPRECATED_ENDPOINT = "DEPRECATED_ENDPOINT"
    HTTP_EXCEPTION = "HTTP_EXCEPTION"
    INTERNAL_ERROR = "INTERNAL_ERROR"
